### ISSUE TITLE
Repository Mirror

### ISSUE THREAD

**Issue by ChristianMurphy** [aecepoglu/unified-language-server#2]
Hey @aecepoglu! :wave: 
Per our prior discussion, tried to move this repo to the https://github.com/unifiedjs org.
Ran into some issues with not having access to transfer the repo, so mirrored the commits for now to https://github.com/unifiedjs/unified-language-server

Feel free to reach out with any questions or concerns.

**Comment by aecepoglu** [comment]
all good. Enjoy.
